### PR TITLE
Positioning floating

### PR DESCRIPTION
**Pull request by majovanilla**
Initial pull request.
Checking linters.

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under the review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Splendid Work :clap: :clap: . However, some requirements that's prevents your project's approval needs to be implemented:

#### Page structure

##### Navigation bar

* [x] It has the NY Times image logo embedded in the **center**.
* [x] The NY Times logo is a **link**.

##### Footer

* [x] It should have a fixed position (it sticks to the bottom part of the screen).

#### Implementation details

* [x] Elements aligned with [float](https://css-tricks.com/all-about-floats/).
- The Big image is aligned using absolute positioning :no_entry_sign: .
* [x] It uses [`<aside>` tag](https://www.w3schools.com/tags/tag_aside.asp) for `Editor's picks` section on the righmost side. Again, using floats :no_entry_sign: 

### General notes:
* [x] Please fix your linting errors that resides in the your stylesheet file.
* [x] Run you `index.html` file through the [Validator](validator.w3.org) and fix the errors.

### And that's it :relieved: . When finished implementing the above, kindly resubmit another code review request. Keep up the good work :muscle: :muscle: .

**Comment by majovanilla** [comment]
We changed all the requirements except for the footer.
The footer of the NY Times webpage is not fixed, at least not the real footer.
There's a subscribe add that appears fixed to the bottom, but since the instructions said that we had to ignore the adds, so we did.

**Comment by samgaco** [comment]
#### Hi @majovainilla and @euqueme :+1: 

#### Your project looks great and the amount of effort you've put on it can be appreciated. :medal_sports: 

I get your point, that might not be the real footer. But, since **it is an ad** from the very same website would be good to implement it. Actually, **is the last requirement necessary** so we can give you the approval.

> ##### Footer
> * [x]  It should have a fixed position (it sticks to the bottom part of the screen).

#### So please :pray: implement that change and submit back for another code review. I am sorry for reinforcing this point on which you are disagreeing but I hope you understand the case. Keep up the good work!! :muscle:

**Comment by euqueme** [comment]
The fixed NYT  ad bar was added on top of the footer as requested.

**Review by uche-inyama — APPROVED** [review]
#### Nice work ladies :medal_sports: 
You have implemented all the changes as requested, go ahead and merge to the master branch  :muscle: 

#### Observation:
- [x]  Endeavor to use the concept of semantic html, consistently through out your html projects. 

#### That's it :+1: :raised_hands:

**Pull request merged**
